# This is a config for E2B sandbox template.
# You can use template ID (cn9jfl7vpthtxv69zivu) or template name (lovable-nextjs-v5) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lovable-nextjs-v5") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-nextjs-v5") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-nextjs-v5')

team_id = "289ce819-f331-4aed-a5c8-a094194c00ed"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-nextjs-v5"
template_id = "cn9jfl7vpthtxv69zivu"
